### ISSUE TITLE
Popup Screen just shows Loading

### ISSUE THREAD

**Issue by lukzluthor** [aztemi/wc-solana-pay#17]
When attempting to process a payment I get a white popup that says loading and it just hangs?
![Screenshot 2023-10-11 at 6 27 43 PM](https://github.com/aztemi/wc-solana-pay/assets/15012650/2dc91c11-c394-4e2f-8457-c5c9ccd21f5e)

Wordpress 6.3.1
Wow Commerce 8.2.0
Pay With SOL 2.2.1

**Comment by t4top** [comment]
Apologies for the delayed feedback. This issue has been resolved with https://github.com/aztemi/wc-solana-pay/pull/20. Please try the latest release of the plugin.
